export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ITEMS_START = "ITEMS_START";
export const GET_ITEMS_SUCCESS = "GET_ITEMS_SUCCESS";
export const GET_ITEMS_FAIL = "GET_ITEMS_FAIL";
export const ADD_ITEM_SUCCESS = "ADD_ITEM_SUCCESS";
export const ADD_ITEM_FAIL = "ADD_ITEM_FAIL";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const REMOVE_ITEM_FAIL = "REMOVE_ITEM_FAIL";
export const UPDATE_ITEM_SUCCESS = "UPDATE_ITEM_SUCCESS";
export const UPDATE_ITEM_FAIL = "UPDATE_ITEM_FAIL";

export const TOGGLE_FORM_DISPLAY_SUCCESS = "TOGGLE_FORM_DISPLAY";
export const TOGGLE_FORM_DISPLAY_FAIL = "TOGGLE_FORM_DISPLAY_FAIL";

export const PANTRY_START = 'PANTRY_START';
export const ADD_TO_PANTRY_SUCCESS = 'ADD_TO_PANTRY_SUCCESS';
export const ADD_TO_PANTRY_FAIL = 'ADD_TO_PANTRY_FAIL';
export const REMOVE_FROM_PANTRY_SUCCESS = 'REMOVE_FROM_PANTRY_SUCCESS';
export const REMOVE_FROM_PANTRY_FAIL = 'REMOVE_FROM_PANTRY_FAIL';
export const GET_PANTRY_SUCCESS = 'GET_PANTRY_SUCCESS';
export const GET_PANTRY_FAIL = 'GET_PANTRY_FAIL';